import { Injectable, Logger } from '@nestjs/common';
import {
  UserPublishedPostRepository,
  type PublishedPostStyleSample,
} from '../../repositories/user-published-post.repository';

const MIN_USABLE_SAMPLES = 2;
const MAX_EXAMPLES_IN_PROMPT = 5;
const MIN_CAPTION_CHARS = 80;
const MAX_EXAMPLE_CHARS = 700;

/**
 * "Learn from your past published posts" (Postiz-inspired, task #1132).
 *
 * Reads the captions a user actually published and assembles a compact system-
 * prompt block so the text LLM mirrors the user's real hook style, sentence
 * rhythm, vocabulary, emoji + formatting habits on the next generation. This is
 * automated data-driven personalization — complementary to, and distinct from,
 * the manual brand-kit voice examples.
 */
@Injectable()
export class PostStyleLearningService {
  private readonly logger = new Logger(PostStyleLearningService.name);

  constructor(private readonly repo: UserPublishedPostRepository) {}

  /**
   * Returns a ready-to-inject system-prompt block, or `undefined` when there
   * isn't enough signal yet. Always best-effort — never throws into the
   * generation path.
   */
  async buildStyleProfileBlock(
    userId: string,
    platform: string,
  ): Promise<string | undefined> {
    if (!userId || userId === 'anonymous') return undefined;

    try {
      // Prefer TOP-PERFORMING posts (engagement_score DESC NULLS LAST, then
      // recency). Until the engagement-sync cron has scored any posts, every
      // score is null and this returns exactly the recency order — so behavior
      // is identical to the previous recency-only approach as a fallback, and
      // automatically upgrades to engagement ranking once data exists.
      let samples = await this.repo.getTopPerformingSamples(
        userId,
        platform,
        12,
      );
      if (samples.length < MIN_USABLE_SAMPLES) {
        const fallback = await this.repo.getFallbackFromGeneratedContent(
          userId,
          12,
        );
        if (fallback.length > samples.length) samples = fallback;
      }

      const examples = this.selectExamples(samples);
      if (examples.length < MIN_USABLE_SAMPLES) {
        this.logger.log(
          `Past-post style: not enough usable samples for user (have ${examples.length}); skipping style block`,
        );
        return undefined;
      }

      const engagementRanked = samples.some(
        (s) => s.engagementScore != null && s.engagementScore > 0,
      );
      this.logger.log(
        `Past-post style injected: ${examples.length} ${engagementRanked ? 'top-performing' : 'recent'} example(s) for ${platform}`,
      );
      return this.formatBlock(examples);
    } catch (e) {
      this.logger.warn(
        `Past-post style skipped: ${(e as Error).message}`,
      );
      return undefined;
    }
  }

  private selectExamples(samples: PublishedPostStyleSample[]): string[] {
    const seen = new Set<string>();
    const picked: string[] = [];

    for (const sample of samples) {
      const cleaned = this.cleanCaption(sample.caption);
      if (cleaned.length < MIN_CAPTION_CHARS) continue;

      const dedupeKey = cleaned.slice(0, 120).toLowerCase();
      if (seen.has(dedupeKey)) continue;
      seen.add(dedupeKey);

      picked.push(this.truncate(cleaned, MAX_EXAMPLE_CHARS));
      if (picked.length >= MAX_EXAMPLES_IN_PROMPT) break;
    }

    return picked;
  }

  private cleanCaption(raw: string): string {
    return (raw || '')
      // Strip our own provenance/footer markers if they ever leak into stored text.
      .replace(/\n*[—-]\s*Generated by[\s\S]*$/i, '')
      .replace(/\u00a0/g, ' ')
      .trim();
  }

  private truncate(text: string, max: number): string {
    if (text.length <= max) return text;
    return `${text.slice(0, max).trimEnd()}…`;
  }

  private formatBlock(examples: string[]): string {
    const lines: string[] = [
      '--- YOUR PAST POSTS (the user actually published these) ---',
      'These are real posts this user published and stands behind. Learn their',
      'personal style from them and write the new post so it feels like the same',
      'author wrote it:',
      '  • Match the hook style and how they open a post.',
      '  • Match sentence rhythm, length, and paragraph/line-break habits.',
      '  • Match their vocabulary, tone, and emoji usage (amount + placement).',
      'Do NOT copy these posts or reuse their topics — only mirror the style.',
      'When this conflicts with the brand voice block, the brand voice wins.',
      '',
    ];

    examples.forEach((example, i) => {
      lines.push(`Example ${i + 1}:`);
      lines.push('"""');
      lines.push(example);
      lines.push('"""');
      lines.push('');
    });

    lines.push('--- END YOUR PAST POSTS ---');
    return lines.join('\n');
  }
}
